### ISSUE TITLE
Upgrade dependency yaml_elixir to 2.0

### ISSUE THREAD

**Issue by JediLuke** [sebastiandedeyne/yaml_front_matter#2]
When doing mix deps.get I see the following warning

```
  yaml_elixir 1.4.0 RETIRED!
    (other) This version provides breaking changes and 2.0.0 should be use instead.
```

yaml_elixir is indeed up to 2.0 now, so maybe you want to look at upgrading. Hopefully it doesn't break anything :)

**Comment by sebastiandedeyne** [comment]
Thanks for the heads up!

Upgraded and did some housekeeping. Tagged version 1.0.0 with the changes.
